use std::collections::BTreeSet;
use std::sync::{Arc, Mutex};
use std::thread;

use elitesql_core::{Db, Error, QueryOutput, Record, Value};

fn rows(output: QueryOutput) -> (Vec<String>, Vec<Vec<Value>>) {
    match output {
        QueryOutput::Rows { columns, rows } => (columns, rows),
        other => panic!("expected rows, got {other:?}"),
    }
}

fn identity_from(output: QueryOutput) -> i64 {
    let (_, rows) = rows(output);
    assert_eq!(rows.len(), 1);
    match rows[0][0] {
        Value::Int64(value) => value,
        ref other => panic!("expected identity int, got {other:?}"),
    }
}

#[test]
fn auto_increment_and_standard_identity_generate_and_return_values() {
    let dir = tempfile::tempdir().unwrap();
    let db = Db::create(dir.path().join("identity.esql")).unwrap();
    db.query("CREATE TABLE docs (doc_id int AUTO_INCREMENT, title text NOT NULL)")
        .unwrap();
    db.query(
        "CREATE TABLE events (event_id int GENERATED BY DEFAULT AS IDENTITY, name text NOT NULL)",
    )
    .unwrap();

    assert_eq!(
        identity_from(
            db.query("INSERT INTO docs (title) VALUES ('one') RETURNING doc_id")
                .unwrap()
        ),
        1
    );
    assert_eq!(
        identity_from(
            db.query("INSERT INTO docs (title) VALUES ('two') RETURNING doc_id")
                .unwrap()
        ),
        2
    );
    assert_eq!(
        identity_from(
            db.query("INSERT INTO events (name) VALUES ('created') RETURNING event_id")
                .unwrap()
        ),
        1
    );

    let (columns, returned) = rows(
        db.query("INSERT INTO docs (title) VALUES ('all') RETURNING *")
            .unwrap(),
    );
    assert_eq!(columns, vec!["id", "doc_id", "title"]);
    assert_eq!(returned[0][1], Value::Int64(3));
    assert_eq!(returned[0][2], Value::Text("all".into()));
    assert!(matches!(&returned[0][0], Value::Text(id) if id.len() == 26));

    let QueryOutput::InsertedIdentity {
        ids,
        column,
        values,
    } = db
        .query("INSERT INTO docs (title) VALUES ('legacy response')")
        .unwrap()
    else {
        panic!("INSERT without RETURNING must keep the legacy response")
    };
    assert_eq!(ids.len(), 1);
    assert_eq!(column, "doc_id");
    assert_eq!(values, vec![4]);
}

#[test]
fn explicit_identity_advances_sequence_and_is_immutable_and_unique() {
    let dir = tempfile::tempdir().unwrap();
    let db = Db::create(dir.path().join("explicit.esql")).unwrap();
    db.query("CREATE TABLE docs (doc_id int AUTO_INCREMENT, title text NOT NULL)")
        .unwrap();

    assert_eq!(
        identity_from(
            db.query("INSERT INTO docs (doc_id, title) VALUES (50, 'imported') RETURNING doc_id")
                .unwrap()
        ),
        50
    );
    assert_eq!(
        identity_from(
            db.query("INSERT INTO docs (title) VALUES ('next') RETURNING doc_id")
                .unwrap()
        ),
        51
    );
    assert!(matches!(
        db.query("INSERT INTO docs (doc_id, title) VALUES (50, 'duplicate')"),
        Err(Error::UniqueViolation { .. })
    ));
    assert!(matches!(
        db.query("UPDATE docs SET doc_id = 70 WHERE doc_id = 50"),
        Err(Error::InvalidArgument(message)) if message.contains("cannot be updated")
    ));
    assert!(db
        .query("INSERT INTO docs (doc_id, title) VALUES (0, 'bad')")
        .is_err());
}

#[test]
fn rollback_may_leave_a_gap_but_never_reuses_in_process() {
    let dir = tempfile::tempdir().unwrap();
    let db = Db::create(dir.path().join("rollback.esql")).unwrap();
    db.query("CREATE TABLE docs (doc_id int AUTO_INCREMENT, title text NOT NULL)")
        .unwrap();

    let mut tx = db.begin();
    let mut record = Record::new();
    record.insert("title".into(), Value::Text("rolled back".into()));
    let id = tx.insert("docs", record).unwrap();
    assert_eq!(
        tx.get("docs", &id).unwrap().unwrap()["doc_id"],
        Value::Int64(1)
    );
    tx.rollback();

    assert_eq!(
        identity_from(
            db.query("INSERT INTO docs (title) VALUES ('committed') RETURNING doc_id")
                .unwrap()
        ),
        2
    );
}

#[test]
fn high_water_survives_wal_checkpoint_delete_and_reopen() {
    let dir = tempfile::tempdir().unwrap();
    let path = dir.path().join("recovery.esql");
    {
        let db = Db::create(&path).unwrap();
        db.query("CREATE TABLE docs (doc_id int AUTO_INCREMENT, title text NOT NULL)")
            .unwrap();
        let (_, returned) = rows(
            db.query("INSERT INTO docs (title) VALUES ('one'), ('two') RETURNING id, doc_id")
                .unwrap(),
        );
        let second_id = match &returned[1][0] {
            Value::Text(id) => id.clone(),
            other => panic!("expected id, got {other:?}"),
        };
        db.checkpoint().unwrap();
        db.query_params("DELETE FROM docs WHERE id = %s", &[Value::Text(second_id)])
            .unwrap();
        db.checkpoint().unwrap();
    }

    let db = Db::open(&path).unwrap();
    assert_eq!(
        identity_from(
            db.query("INSERT INTO docs (title) VALUES ('three') RETURNING doc_id")
                .unwrap()
        ),
        3
    );
}

#[test]
fn concurrent_writers_receive_distinct_identity_values() {
    let dir = tempfile::tempdir().unwrap();
    let db = Arc::new(Db::create(dir.path().join("concurrent.esql")).unwrap());
    db.query("CREATE TABLE docs (doc_id int AUTO_INCREMENT, title text NOT NULL)")
        .unwrap();
    let values = Arc::new(Mutex::new(Vec::new()));
    let mut workers = Vec::new();
    for worker in 0..100 {
        let db = db.clone();
        let values = values.clone();
        workers.push(thread::spawn(move || {
            let output = db
                .query_params(
                    "INSERT INTO docs (title) VALUES (%s) RETURNING doc_id",
                    &[Value::Text(format!("doc-{worker}"))],
                )
                .unwrap();
            values.lock().unwrap().push(identity_from(output));
        }));
    }
    for worker in workers {
        worker.join().unwrap();
    }

    let values = values.lock().unwrap();
    let unique: BTreeSet<i64> = values.iter().copied().collect();
    assert_eq!(values.len(), 100);
    assert_eq!(unique.len(), 100);
    assert_eq!(db.scan("docs").unwrap().len(), 100);
}

#[test]
fn identity_schema_errors_are_explicit() {
    let dir = tempfile::tempdir().unwrap();
    let db = Db::create(dir.path().join("schema-errors.esql")).unwrap();
    assert!(matches!(
        db.query("CREATE TABLE bad (value text AUTO_INCREMENT)"),
        Err(Error::Sql(message)) if message.contains("requires an int")
    ));
    assert!(matches!(
        db.query("CREATE TABLE bad (a int AUTO_INCREMENT, b int AUTO_INCREMENT)"),
        Err(Error::SchemaViolation(message)) if message.contains("at most one")
    ));
    assert!(matches!(
        db.query("CREATE TABLE bad (a int AUTO_INCREMENT DEFAULT 1)"),
        Err(Error::Sql(message)) if message.contains("cannot also have DEFAULT")
    ));
}

#[test]
fn mysql_primary_key_spelling_is_accepted_for_an_identity() {
    let dir = tempfile::tempdir().unwrap();
    let db = Db::create(dir.path().join("primary-identity.esql")).unwrap();
    db.query("CREATE TABLE docs (document_id int PRIMARY KEY AUTO_INCREMENT, title text)")
        .unwrap();
    assert_eq!(
        identity_from(
            db.query("INSERT INTO docs (title) VALUES ('compatible') RETURNING document_id")
                .unwrap()
        ),
        1
    );
}

#[test]
fn conventional_id_auto_increment_primary_key_is_supported() {
    let dir = tempfile::tempdir().unwrap();
    let db = Db::create(dir.path().join("conventional-id.esql")).unwrap();
    db.query("CREATE TABLE users (id int AUTO_INCREMENT PRIMARY KEY, name text NOT NULL)")
        .unwrap();
    let (columns, returned) = rows(
        db.query("INSERT INTO users (name) VALUES ('Ada') RETURNING id, name")
            .unwrap(),
    );
    assert_eq!(columns, vec!["id", "name"]);
    assert_eq!(
        returned,
        vec![vec![Value::Int64(1), Value::Text("Ada".into())]]
    );
    assert_eq!(
        rows(db.query("SELECT id, name FROM users WHERE id = 1").unwrap()).1,
        vec![vec![Value::Int64(1), Value::Text("Ada".into())]]
    );
    assert_eq!(
        rows(db.query("SELECT * FROM users").unwrap()),
        (
            vec!["id".into(), "name".into()],
            vec![vec![Value::Int64(1), Value::Text("Ada".into())]],
        )
    );
    db.query("UPDATE users SET name = 'Grace' WHERE id = 1")
        .unwrap();
    assert_eq!(
        rows(db.query("SELECT id, name FROM users").unwrap()).1,
        vec![vec![Value::Int64(1), Value::Text("Grace".into())]]
    );
    db.query("DELETE FROM users WHERE id = 1").unwrap();
    assert!(rows(db.query("SELECT id FROM users").unwrap()).1.is_empty());
}

#[test]
fn declared_id_can_be_the_target_of_a_foreign_key() {
    let dir = tempfile::tempdir().unwrap();
    let db = Db::create(dir.path().join("declared-id-fk.esql")).unwrap();
    db.query("CREATE TABLE parents (id int AUTO_INCREMENT PRIMARY KEY, name text)")
        .unwrap();
    db.query("CREATE TABLE children (parent_id int REFERENCES parents(id), name text)")
        .unwrap();
    db.query("INSERT INTO parents (name) VALUES ('parent')")
        .unwrap();
    db.query("INSERT INTO children (parent_id, name) VALUES (1, 'child')")
        .unwrap();
    assert_eq!(
        rows(
            db.query("SELECT children.name FROM children JOIN parents ON children.parent_id = parents.id")
                .unwrap(),
        )
        .1,
        vec![vec![Value::Text("child".into())]]
    );
}

#[test]
fn declaring_the_implicit_text_primary_key_is_redundant() {
    let dir = tempfile::tempdir().unwrap();
    let db = Db::create(dir.path().join("declared-id.esql")).unwrap();
    db.query("CREATE TABLE docs (id text PRIMARY KEY, title text NOT NULL)")
        .unwrap();
    let (_, returned) = rows(
        db.query("INSERT INTO docs (title) VALUES ('declared') RETURNING id, title")
            .unwrap(),
    );
    assert!(matches!(&returned[0][0], Value::Text(id) if id.len() == 26));
    assert_eq!(returned[0][1], Value::Text("declared".into()));
}
