//! ClawDB core engine — Phase 0 prototype.
//!
//! A tiny operational database for AI-native apps. This phase validates the
//! append-only storage core and the API ergonomics:
//!
//! - Self-contained database directory (`app.clawdb/`).
//! - V1 scalar types: bool, int64, float64, text, blob, timestamp, json.
//! - Insert/get/update/delete with per-record versioning and tombstones.
//! - ULID text primary keys generated by the engine.
//! - Snapshot reads by version.
//! - In-memory primary index rebuilt on open; CRC32 on every entry.
//!
//! Explicitly out of scope for Phase 0 (arrives in Phase 1): WAL, fsync
//! durability modes, MVCC transactions, secondary indexes, compaction.
//!
//! ```
//! use clawdb_core::{Column, ColumnType, Db, Record, TableSchema, Value};
//!
//! let dir = tempfile::tempdir().unwrap();
//! let db = Db::create(dir.path().join("app.clawdb")).unwrap();
//! db.create_table(TableSchema::new(
//!     "docs",
//!     vec![
//!         Column::new("title", ColumnType::Text).not_null(),
//!         Column::new("score", ColumnType::Int64),
//!     ],
//! ))
//! .unwrap();
//!
//! let mut record = Record::new();
//! record.insert("title".into(), Value::Text("hello".into()));
//! record.insert("score".into(), Value::Int64(42));
//! let id = db.insert("docs", record).unwrap();
//!
//! let read = db.get("docs", &id).unwrap().unwrap();
//! assert_eq!(read["title"], Value::Text("hello".into()));
//! ```

mod db;
mod error;
mod schema;
mod segment;
mod value;

pub use db::{Db, Record, Snapshot};
pub use error::{Error, Result};
pub use schema::{Column, TableSchema};
pub use value::{ColumnType, Value};
