use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

use crate::error::{Error, Result};
use crate::value::ColumnType;

pub(crate) const FORMAT_VERSION: u32 = 2;

/// Reserved implicit primary-key column. Every record has a `text` id
/// (a ULID generated by the engine when the caller does not provide one).
pub(crate) const ID_COLUMN: &str = "id";

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Column {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: ColumnType,
    #[serde(default = "default_true")]
    pub nullable: bool,
    /// Dimension for vector columns; None for every other type.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dim: Option<usize>,
}

fn default_true() -> bool {
    true
}

impl Column {
    pub fn new(name: impl Into<String>, ty: ColumnType) -> Self {
        Column {
            name: name.into(),
            ty,
            nullable: true,
            dim: None,
        }
    }

    /// A `vector<float32, dim>` column.
    pub fn vector(name: impl Into<String>, dim: usize) -> Self {
        Column {
            name: name.into(),
            ty: ColumnType::Vector,
            nullable: true,
            dim: Some(dim),
        }
    }

    pub fn not_null(mut self) -> Self {
        self.nullable = false;
        self
    }
}

/// A secondary index over one column. Secondary indexes reflect the latest
/// committed state (not historical snapshot versions) in Phase 1.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IndexDef {
    pub column: String,
    pub unique: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TableSchema {
    pub name: String,
    pub columns: Vec<Column>,
    #[serde(default)]
    pub indexes: Vec<IndexDef>,
    #[serde(default)]
    pub vector_indexes: Vec<crate::vector::VectorIndexDef>,
}

impl TableSchema {
    pub fn new(name: impl Into<String>, columns: Vec<Column>) -> Self {
        TableSchema {
            name: name.into(),
            columns,
            indexes: Vec::new(),
            vector_indexes: Vec::new(),
        }
    }

    pub(crate) fn column(&self, name: &str) -> Option<&Column> {
        self.columns.iter().find(|c| c.name == name)
    }

    pub(crate) fn validate(&self) -> Result<()> {
        if self.name.is_empty() {
            return Err(Error::InvalidArgument("table name must not be empty".into()));
        }
        for (i, col) in self.columns.iter().enumerate() {
            if col.name.is_empty() {
                return Err(Error::InvalidArgument("column name must not be empty".into()));
            }
            if col.name == ID_COLUMN {
                return Err(Error::InvalidArgument(format!(
                    "column name '{ID_COLUMN}' is reserved for the implicit primary key"
                )));
            }
            if self.columns[..i].iter().any(|c| c.name == col.name) {
                return Err(Error::InvalidArgument(format!(
                    "duplicate column name '{}'",
                    col.name
                )));
            }
            match (col.ty, col.dim) {
                (ColumnType::Vector, Some(d)) if d >= 1 => {}
                (ColumnType::Vector, _) => {
                    return Err(Error::InvalidArgument(format!(
                        "vector column '{}' needs a dimension >= 1",
                        col.name
                    )))
                }
                (_, Some(_)) => {
                    return Err(Error::InvalidArgument(format!(
                        "column '{}' is not a vector; it cannot have a dimension",
                        col.name
                    )))
                }
                _ => {}
            }
        }
        Ok(())
    }
}

/// The table catalog, persisted as `catalog.json` in the database directory.
/// Written atomically (temp file + rename), same discipline the manifest will
/// use in Phase 1.
#[derive(Debug, Serialize, Deserialize)]
pub(crate) struct Catalog {
    pub format_version: u32,
    pub tables: Vec<TableSchema>,
}

impl Catalog {
    pub fn new() -> Self {
        Catalog {
            format_version: FORMAT_VERSION,
            tables: Vec::new(),
        }
    }

    pub fn table(&self, name: &str) -> Option<&TableSchema> {
        self.tables.iter().find(|t| t.name == name)
    }

    pub fn load(path: &Path) -> Result<Self> {
        let bytes = fs::read(path)?;
        let catalog: Catalog = serde_json::from_slice(&bytes)
            .map_err(|e| Error::Corrupt(format!("invalid catalog: {e}")))?;
        if catalog.format_version != FORMAT_VERSION {
            return Err(Error::Corrupt(format!(
                "unsupported format_version {} (expected {FORMAT_VERSION})",
                catalog.format_version
            )));
        }
        Ok(catalog)
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let tmp = path.with_extension("json.tmp");
        let bytes = serde_json::to_vec_pretty(self).expect("catalog always serializes");
        fs::write(&tmp, bytes)?;
        fs::rename(&tmp, path)?;
        Ok(())
    }
}
