use serde::{Deserialize, Serialize};
use std::fs::{self, File};
use std::io::Write;
use std::path::Path;
use std::time::{SystemTime, UNIX_EPOCH};

use crate::error::{Error, Result};
use crate::value::{ColumnType, Value};

pub(crate) const FORMAT_VERSION: u32 = 2;

/// Reserved implicit primary-key column. Every record has a `text` id
/// (a ULID generated by the engine when the caller does not provide one).
pub(crate) const ID_COLUMN: &str = "id";

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Column {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: ColumnType,
    #[serde(default = "default_true")]
    pub nullable: bool,
    /// Dimension for vector columns; None for every other type.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dim: Option<usize>,
    /// Optional Unicode scalar length limit for varchar(N).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_length: Option<usize>,
    /// Allowed text values for enum(...), stored in declaration order.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub enum_values: Option<Vec<String>>,
    /// Value substituted when a write omits the column, stored in the JSON
    /// encoding of [`crate::jsonio`]. `None` means "no default": an omitted
    /// column becomes NULL. Use [`Column::with_default`] to set it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default: Option<serde_json::Value>,
    /// Dynamic UTC timestamp evaluated when a write omits this column.
    #[serde(default, skip_serializing_if = "is_false")]
    pub default_current_timestamp: bool,
    /// Integer identity generated by the engine when the column is omitted.
    /// The implicit text `id` remains the physical primary key.
    #[serde(default, skip_serializing_if = "is_false")]
    pub identity: bool,
}

fn default_true() -> bool {
    true
}

fn is_false(value: &bool) -> bool {
    !*value
}

impl Column {
    pub fn new(name: impl Into<String>, ty: ColumnType) -> Self {
        Column {
            name: name.into(),
            ty,
            nullable: true,
            dim: None,
            max_length: None,
            enum_values: None,
            default: None,
            default_current_timestamp: false,
            identity: false,
        }
    }

    /// A `vector<float32, dim>` column.
    pub fn vector(name: impl Into<String>, dim: usize) -> Self {
        Column {
            name: name.into(),
            ty: ColumnType::Vector,
            nullable: true,
            dim: Some(dim),
            max_length: None,
            enum_values: None,
            default: None,
            default_current_timestamp: false,
            identity: false,
        }
    }

    pub fn not_null(mut self) -> Self {
        self.nullable = false;
        self
    }

    pub fn varchar(name: impl Into<String>, max_length: usize) -> Self {
        let mut column = Self::new(name, ColumnType::Text);
        column.max_length = Some(max_length);
        column
    }

    pub fn enumeration(name: impl Into<String>, values: Vec<String>) -> Self {
        let mut column = Self::new(name, ColumnType::Text);
        column.enum_values = Some(values);
        column
    }

    /// Set the value used when a write omits this column. `ALTER TABLE ... ADD
    /// COLUMN` also backfills existing records with it.
    pub fn with_default(mut self, value: &Value) -> Self {
        self.default = Some(crate::jsonio::value_to_json(value));
        self.default_current_timestamp = false;
        self
    }

    pub fn with_current_timestamp_default(mut self) -> Self {
        self.default = None;
        self.default_current_timestamp = true;
        self
    }

    /// Make this `int` column an engine-generated identity. Identity columns
    /// are non-nullable and may still receive explicit positive values during
    /// imports (`GENERATED BY DEFAULT` semantics).
    pub fn identity(mut self) -> Self {
        self.identity = true;
        self.nullable = false;
        self.default = None;
        self.default_current_timestamp = false;
        self
    }

    /// The declared default as a `Value`, or `Value::Null` when there is none.
    pub(crate) fn default_value(&self) -> Result<Value> {
        if self.default_current_timestamp {
            let micros = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .map_err(|_| Error::SchemaViolation("system clock is before Unix epoch".into()))?
                .as_micros();
            return Ok(Value::Timestamp(i64::try_from(micros).map_err(|_| {
                Error::SchemaViolation("current timestamp is outside int64 range".into())
            })?));
        }
        match &self.default {
            None => Ok(Value::Null),
            Some(j) => crate::jsonio::json_to_value_for_type(j, self.ty),
        }
    }

    pub(crate) fn validate(&self) -> Result<()> {
        if self.name.is_empty() {
            return Err(Error::InvalidArgument(
                "column name must not be empty".into(),
            ));
        }
        if self.name == ID_COLUMN && !self.identity {
            return Err(Error::InvalidArgument(format!(
                "column name '{ID_COLUMN}' is reserved unless it is an identity column"
            )));
        }
        match (self.ty, self.dim) {
            (ColumnType::Vector, Some(d)) if d >= 1 => {}
            (ColumnType::Vector, _) => {
                return Err(Error::InvalidArgument(format!(
                    "vector column '{}' needs a dimension >= 1",
                    self.name
                )))
            }
            (_, Some(_)) => {
                return Err(Error::InvalidArgument(format!(
                    "column '{}' is not a vector; it cannot have a dimension",
                    self.name
                )))
            }
            _ => {}
        }
        if let Some(max_length) = self.max_length {
            if self.ty != ColumnType::Text || max_length == 0 {
                return Err(Error::SchemaViolation(format!(
                    "varchar constraint on '{}' requires text and a length >= 1",
                    self.name
                )));
            }
        }
        if let Some(values) = &self.enum_values {
            if self.ty != ColumnType::Text || values.is_empty() {
                return Err(Error::SchemaViolation(format!(
                    "enum constraint on '{}' requires text and at least one value",
                    self.name
                )));
            }
            for (index, value) in values.iter().enumerate() {
                if values[..index].contains(value) {
                    return Err(Error::SchemaViolation(format!(
                        "enum constraint on '{}' contains duplicate value '{value}'",
                        self.name
                    )));
                }
            }
        }
        if self.identity {
            if self.ty != ColumnType::Int64 {
                return Err(Error::SchemaViolation(format!(
                    "identity column '{}' must have type int",
                    self.name
                )));
            }
            if self.nullable {
                return Err(Error::SchemaViolation(format!(
                    "identity column '{}' must be NOT NULL",
                    self.name
                )));
            }
            if self.default.is_some() || self.default_current_timestamp {
                return Err(Error::SchemaViolation(format!(
                    "identity column '{}' cannot also have DEFAULT",
                    self.name
                )));
            }
        }
        if self.default_current_timestamp && self.ty != ColumnType::Timestamp {
            return Err(Error::SchemaViolation(format!(
                "CURRENT_TIMESTAMP default on '{}' requires a timestamp column",
                self.name
            )));
        }
        if self.default_current_timestamp && self.default.is_some() {
            return Err(Error::SchemaViolation(format!(
                "column '{}' cannot have two defaults",
                self.name
            )));
        }
        if self.default.is_none() {
            return Ok(());
        }
        let value = self.default_value()?;
        if value.is_null() {
            if !self.nullable {
                return Err(Error::SchemaViolation(format!(
                    "column '{}' is NOT NULL; its default cannot be NULL",
                    self.name
                )));
            }
            return Ok(());
        }
        if !value.matches(self.ty) {
            return Err(Error::SchemaViolation(format!(
                "default for column '{}' is not a {} value",
                self.name, self.ty
            )));
        }
        if let (Value::Vector(v), Some(dim)) = (&value, self.dim) {
            if v.len() != dim {
                return Err(Error::SchemaViolation(format!(
                    "default for column '{}' has dimension {}, expected {dim}",
                    self.name,
                    v.len()
                )));
            }
        }
        if let Value::Text(text) = &value {
            if let Some(max_length) = self.max_length {
                if text.chars().count() > max_length {
                    return Err(Error::SchemaViolation(format!(
                        "default for column '{}' exceeds varchar({max_length})",
                        self.name
                    )));
                }
            }
            if let Some(values) = &self.enum_values {
                if !values.contains(text) {
                    return Err(Error::SchemaViolation(format!(
                        "default for column '{}' is not an allowed enum value",
                        self.name
                    )));
                }
            }
        }
        Ok(())
    }
}

/// A secondary index over one column. Secondary indexes reflect the latest
/// committed state (not historical snapshot versions) in Phase 1.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct IndexDef {
    pub column: String,
    pub unique: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReferentialAction {
    Restrict,
    Cascade,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ForeignKeyDef {
    pub column: String,
    pub referenced_table: String,
    pub referenced_column: String,
    #[serde(default = "default_restrict")]
    pub on_delete: ReferentialAction,
}

fn default_restrict() -> ReferentialAction {
    ReferentialAction::Restrict
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TableSchema {
    pub name: String,
    pub columns: Vec<Column>,
    #[serde(default)]
    pub indexes: Vec<IndexDef>,
    #[serde(default)]
    pub vector_indexes: Vec<crate::vector::VectorIndexDef>,
    #[serde(default)]
    pub text_indexes: Vec<crate::text::TextIndexDef>,
    #[serde(default)]
    pub foreign_keys: Vec<ForeignKeyDef>,
    /// Commit version at which this incarnation of the table was created.
    /// `DROP TABLE` unlinks a table from the catalog without rewriting
    /// segments, so data written by an earlier table of the same name can
    /// still be on disk; every such entry carries a version at or below this
    /// watermark and is ignored on open (and dropped by the next compaction).
    /// Set by `create_table`; a value provided by the caller is overwritten.
    #[serde(default, skip_serializing_if = "is_zero")]
    pub(crate) epoch: u64,
}

fn is_zero(v: &u64) -> bool {
    *v == 0
}

impl TableSchema {
    pub fn new(name: impl Into<String>, columns: Vec<Column>) -> Self {
        TableSchema {
            name: name.into(),
            columns,
            indexes: Vec::new(),
            vector_indexes: Vec::new(),
            text_indexes: Vec::new(),
            foreign_keys: Vec::new(),
            epoch: 0,
        }
    }

    /// Look up a declared column by name. Tables without a declared `id` also
    /// expose their physical ULID under that name.
    pub fn column(&self, name: &str) -> Option<&Column> {
        self.columns.iter().find(|c| c.name == name)
    }

    /// Whether SQL `id` is the engine's implicit physical ULID rather than a
    /// user-declared column.
    pub(crate) fn has_implicit_id(&self) -> bool {
        self.column(ID_COLUMN).is_none()
    }

    pub(crate) fn validate(&self) -> Result<()> {
        if self.name.is_empty() {
            return Err(Error::InvalidArgument(
                "table name must not be empty".into(),
            ));
        }
        for (i, col) in self.columns.iter().enumerate() {
            col.validate()?;
            if self.columns[..i].iter().any(|c| c.name == col.name) {
                return Err(Error::InvalidArgument(format!(
                    "duplicate column name '{}'",
                    col.name
                )));
            }
        }
        if self.columns.iter().filter(|column| column.identity).count() > 1 {
            return Err(Error::SchemaViolation(format!(
                "table '{}' can have at most one identity column",
                self.name
            )));
        }
        for (index, foreign_key) in self.foreign_keys.iter().enumerate() {
            if self.column(&foreign_key.column).is_none() {
                return Err(Error::SchemaViolation(format!(
                    "foreign key uses unknown column '{}.{}'",
                    self.name, foreign_key.column
                )));
            }
            if self.foreign_keys[..index]
                .iter()
                .any(|previous| previous.column == foreign_key.column)
            {
                return Err(Error::SchemaViolation(format!(
                    "column '{}.{}' has more than one foreign key",
                    self.name, foreign_key.column
                )));
            }
        }
        Ok(())
    }
}

/// The table catalog, persisted as `catalog.json` in the database directory.
/// Written atomically and durably: temp file, fsync, rename, fsync of the
/// directory — the same discipline as the manifest, because DDL correctness
/// depends on a committed catalog surviving a crash.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct Catalog {
    pub format_version: u32,
    pub tables: Vec<TableSchema>,
}

impl Catalog {
    pub fn new() -> Self {
        Catalog {
            format_version: FORMAT_VERSION,
            tables: Vec::new(),
        }
    }

    pub fn table(&self, name: &str) -> Option<&TableSchema> {
        self.tables.iter().find(|t| t.name == name)
    }

    pub fn table_mut(&mut self, name: &str) -> Option<&mut TableSchema> {
        self.tables.iter_mut().find(|t| t.name == name)
    }

    pub fn load(path: &Path) -> Result<Self> {
        let bytes = fs::read(path)?;
        let catalog: Catalog = serde_json::from_slice(&bytes)
            .map_err(|e| Error::Corrupt(format!("invalid catalog: {e}")))?;
        if catalog.format_version != FORMAT_VERSION {
            return Err(Error::Corrupt(format!(
                "unsupported format_version {} (expected {FORMAT_VERSION})",
                catalog.format_version
            )));
        }
        Ok(catalog)
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let tmp = path.with_extension("json.tmp");
        let bytes = serde_json::to_vec_pretty(self).expect("catalog always serializes");
        {
            let mut f = File::create(&tmp)?;
            f.write_all(&bytes)?;
            f.sync_all()?;
        }
        fs::rename(&tmp, path)?;
        if let Some(dir) = path.parent().filter(|p| !p.as_os_str().is_empty()) {
            crate::manifest::fsync_dir(dir)?;
        }
        Ok(())
    }
}
