use serde::{Deserialize, Serialize};
use std::fs::{self, File};
use std::io::Write;
use std::path::Path;

use crate::error::{Error, Result};
use crate::value::{ColumnType, Value};

pub(crate) const FORMAT_VERSION: u32 = 2;

/// Reserved implicit primary-key column. Every record has a `text` id
/// (a ULID generated by the engine when the caller does not provide one).
pub(crate) const ID_COLUMN: &str = "id";

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Column {
    pub name: String,
    #[serde(rename = "type")]
    pub ty: ColumnType,
    #[serde(default = "default_true")]
    pub nullable: bool,
    /// Dimension for vector columns; None for every other type.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub dim: Option<usize>,
    /// Value substituted when a write omits the column, stored in the JSON
    /// encoding of [`crate::jsonio`]. `None` means "no default": an omitted
    /// column becomes NULL. Use [`Column::with_default`] to set it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub default: Option<serde_json::Value>,
}

fn default_true() -> bool {
    true
}

impl Column {
    pub fn new(name: impl Into<String>, ty: ColumnType) -> Self {
        Column {
            name: name.into(),
            ty,
            nullable: true,
            dim: None,
            default: None,
        }
    }

    /// A `vector<float32, dim>` column.
    pub fn vector(name: impl Into<String>, dim: usize) -> Self {
        Column {
            name: name.into(),
            ty: ColumnType::Vector,
            nullable: true,
            dim: Some(dim),
            default: None,
        }
    }

    pub fn not_null(mut self) -> Self {
        self.nullable = false;
        self
    }

    /// Set the value used when a write omits this column. `ALTER TABLE ... ADD
    /// COLUMN` also backfills existing records with it.
    pub fn with_default(mut self, value: &Value) -> Self {
        self.default = Some(crate::jsonio::value_to_json(value));
        self
    }

    /// The declared default as a `Value`, or `Value::Null` when there is none.
    pub(crate) fn default_value(&self) -> Result<Value> {
        match &self.default {
            None => Ok(Value::Null),
            Some(j) => crate::jsonio::json_to_value_for_type(j, self.ty),
        }
    }

    pub(crate) fn validate(&self) -> Result<()> {
        if self.name.is_empty() {
            return Err(Error::InvalidArgument(
                "column name must not be empty".into(),
            ));
        }
        if self.name == ID_COLUMN {
            return Err(Error::InvalidArgument(format!(
                "column name '{ID_COLUMN}' is reserved for the implicit primary key"
            )));
        }
        match (self.ty, self.dim) {
            (ColumnType::Vector, Some(d)) if d >= 1 => {}
            (ColumnType::Vector, _) => {
                return Err(Error::InvalidArgument(format!(
                    "vector column '{}' needs a dimension >= 1",
                    self.name
                )))
            }
            (_, Some(_)) => {
                return Err(Error::InvalidArgument(format!(
                    "column '{}' is not a vector; it cannot have a dimension",
                    self.name
                )))
            }
            _ => {}
        }
        if self.default.is_none() {
            return Ok(());
        }
        let value = self.default_value()?;
        if value.is_null() {
            if !self.nullable {
                return Err(Error::SchemaViolation(format!(
                    "column '{}' is NOT NULL; its default cannot be NULL",
                    self.name
                )));
            }
            return Ok(());
        }
        if !value.matches(self.ty) {
            return Err(Error::SchemaViolation(format!(
                "default for column '{}' is not a {} value",
                self.name, self.ty
            )));
        }
        if let (Value::Vector(v), Some(dim)) = (&value, self.dim) {
            if v.len() != dim {
                return Err(Error::SchemaViolation(format!(
                    "default for column '{}' has dimension {}, expected {dim}",
                    self.name,
                    v.len()
                )));
            }
        }
        Ok(())
    }
}

/// A secondary index over one column. Secondary indexes reflect the latest
/// committed state (not historical snapshot versions) in Phase 1.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct IndexDef {
    pub column: String,
    pub unique: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TableSchema {
    pub name: String,
    pub columns: Vec<Column>,
    #[serde(default)]
    pub indexes: Vec<IndexDef>,
    #[serde(default)]
    pub vector_indexes: Vec<crate::vector::VectorIndexDef>,
    #[serde(default)]
    pub text_indexes: Vec<crate::text::TextIndexDef>,
    /// Commit version at which this incarnation of the table was created.
    /// `DROP TABLE` unlinks a table from the catalog without rewriting
    /// segments, so data written by an earlier table of the same name can
    /// still be on disk; every such entry carries a version at or below this
    /// watermark and is ignored on open (and dropped by the next compaction).
    /// Set by `create_table`; a value provided by the caller is overwritten.
    #[serde(default, skip_serializing_if = "is_zero")]
    pub(crate) epoch: u64,
}

fn is_zero(v: &u64) -> bool {
    *v == 0
}

impl TableSchema {
    pub fn new(name: impl Into<String>, columns: Vec<Column>) -> Self {
        TableSchema {
            name: name.into(),
            columns,
            indexes: Vec::new(),
            vector_indexes: Vec::new(),
            text_indexes: Vec::new(),
            epoch: 0,
        }
    }

    /// Look up a column by name (the implicit `id` is not listed here).
    pub fn column(&self, name: &str) -> Option<&Column> {
        self.columns.iter().find(|c| c.name == name)
    }

    pub(crate) fn validate(&self) -> Result<()> {
        if self.name.is_empty() {
            return Err(Error::InvalidArgument(
                "table name must not be empty".into(),
            ));
        }
        for (i, col) in self.columns.iter().enumerate() {
            col.validate()?;
            if self.columns[..i].iter().any(|c| c.name == col.name) {
                return Err(Error::InvalidArgument(format!(
                    "duplicate column name '{}'",
                    col.name
                )));
            }
        }
        Ok(())
    }
}

/// The table catalog, persisted as `catalog.json` in the database directory.
/// Written atomically and durably: temp file, fsync, rename, fsync of the
/// directory — the same discipline as the manifest, because DDL correctness
/// depends on a committed catalog surviving a crash.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub(crate) struct Catalog {
    pub format_version: u32,
    pub tables: Vec<TableSchema>,
}

impl Catalog {
    pub fn new() -> Self {
        Catalog {
            format_version: FORMAT_VERSION,
            tables: Vec::new(),
        }
    }

    pub fn table(&self, name: &str) -> Option<&TableSchema> {
        self.tables.iter().find(|t| t.name == name)
    }

    pub fn table_mut(&mut self, name: &str) -> Option<&mut TableSchema> {
        self.tables.iter_mut().find(|t| t.name == name)
    }

    pub fn load(path: &Path) -> Result<Self> {
        let bytes = fs::read(path)?;
        let catalog: Catalog = serde_json::from_slice(&bytes)
            .map_err(|e| Error::Corrupt(format!("invalid catalog: {e}")))?;
        if catalog.format_version != FORMAT_VERSION {
            return Err(Error::Corrupt(format!(
                "unsupported format_version {} (expected {FORMAT_VERSION})",
                catalog.format_version
            )));
        }
        Ok(catalog)
    }

    pub fn save(&self, path: &Path) -> Result<()> {
        let tmp = path.with_extension("json.tmp");
        let bytes = serde_json::to_vec_pretty(self).expect("catalog always serializes");
        {
            let mut f = File::create(&tmp)?;
            f.write_all(&bytes)?;
            f.sync_all()?;
        }
        fs::rename(&tmp, path)?;
        if let Some(dir) = path.parent().filter(|p| !p.as_os_str().is_empty()) {
            crate::manifest::fsync_dir(dir)?;
        }
        Ok(())
    }
}
